name: Build and Deploy to stage

on:
  push:
    branches:
      - develop
      - staging
      - 'feature/github-ci'

jobs:
  stage:
    runs-on: ubuntu-latest

    env:
      VUE_APP_IS_DEV: false
      CI_SECRET: ${{ secrets.CI_SECRET }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: holyheld
      SENTRY_PROJECT: move-web-app
      SENTRY_ENVIRONMENT: development

    steps:
      - run: ls -la
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js 14.17.4
        uses: actions/setup-node@v3
        with:
          node-version: 14.17.4
      - name: Install yarn
        run: npm install --global yarn
      - name: Show yarn version
        run: yarn --version

      - name: Prepare files to build static web app
        run: |
          openssl aes-256-cbc -pbkdf2 -iter 100000 -d -k $CI_SECRET -in deploy/keys-stg.enc -out deploy/keys-stg.dec
          mv deploy/keys-stg.dec src/settings/keys.ts

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build app
        run: yarn build-stage

      - name: Install Google Cloud SDK
        run: |
          wget -qO- https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-351.0.0-linux-x86_64.tar.gz | sudo tar xz -C /usr/local
          sudo /usr/local/google-cloud-sdk/install.sh --quiet
          sudo /usr/local/google-cloud-sdk/bin/gcloud components install app-engine-go
      - name: Decrypt deploy key
        run: |
          openssl aes-256-cbc -pbkdf2 -iter 100000 -d -k $CI_SECRET -in deploy/deploykey-stg.enc -out deploy/deploykey-stg.json
          /usr/local/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file deploy/deploykey-stg.json
      - name: Deploy to GAE
        run: |
          mkdir deploy/www
          mv dist/* deploy/www/
          mv deploy/www dist/
          cp deploy/moverwebapp-stg.yaml dist/
          cd dist
          /usr/local/google-cloud-sdk/bin/gcloud app deploy --project mcmannaman-208313 moverwebapp-stg.yaml --promote
      - name: Create release and notify Sentry of deploy
        run: |
          curl -sL https://sentry.io/get-cli/ | bash
          export SENTRY_RELEASE=$(sentry-cli releases propose-version)
          sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
          sentry-cli releases set-commits $SENTRY_RELEASE --auto --ignore-missing
          sentry-cli releases files $SENTRY_RELEASE upload-sourcemaps dist/www/js/*
          sentry-cli releases finalize $SENTRY_RELEASE
          sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_ENVIRONMENT
